server:
  port: 8084
spring:
  application:
    name: goods-web
  thymeleaf:
    cache: false  #模板缓存
  rabbitmq:
    host: 192.168.83.128
    port: 5672
    virtual-host: /leyou
    password: leyou
    username: leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
